# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('uid', models.UUIDField(default=uuid.UUID('f31600db-f10c-4943-8134-c093c33d0e44'), unique=True)),
                ('pin', models.CharField(max_length=2)),
                ('state', models.CharField(choices=[('1', 'HIGH'), ('0', 'LOW')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
