# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20170921_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('657bb52b-a686-41fb-a13c-ff16fa02909b'), unique=True),
        ),
    ]
